### ISSUE TITLE
Support for PowerPC and ARM architectures in Linux builds

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/libmbd-feedstock#17]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Unless there are known issues for libmbd on ppc64le or aarch64 architectures we could add support for those to build DFTB+ with MBD support on conda-forge (see https://conda-forge.org/docs/maintainer/conda_forge_yml.html#provider).

Relevant for https://github.com/conda-forge/dftbplus-feedstock/pull/14

cc @conda-forge/libmbd @aradi

**Comment by awvwgk** [comment]
I think we currently don't run tests in the feedstock build, either upstream can confirm it works on those architectures or we have to implement testing here to make sure the resulting package is usable.

**Comment by jhrmnn** [comment]
Thanks for raising this up. I thought tests are run as part of the conda-forge build. Would that be best added to `build.sh`? I can't confirm if Libmbd compiles and runs on ARM64—I run Libmbd only on Github Actions and AFAIK ARM64 didn't make it there yet.

**Comment by awvwgk** [comment]
The build script runs
https://github.com/conda-forge/libmbd-feedstock/blob/2d23e3c1be0a0683fd982fd12135f6ce074db424/recipe/build.sh#L24

No tests yet.

**Comment by awvwgk** [comment]
It does compile on both [ARM](https://cloud.drone.io/conda-forge/libmbd-feedstock/1) and [PowerPC](https://travis-ci.com/github/conda-forge/libmbd-feedstock/builds/225641180), probably will also run without issues (I guess?).

**Comment by jhrmnn** [comment]
The failing runs fail with
```
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
```
Any know-how transferable from DFTB+ here? Do you run DFTB+ under MPI with CTest?

**Comment by awvwgk** [comment]
Got it working, OpenMP's mpiexec required some environment variables set (https://github.com/conda-forge/libmbd-feedstock/pull/18/commits/edb0dcb0f33058ef13ccdedb94f03d8d0e6aee42).

**Comment by jhrmnn** [comment]
Thanks!
