### ISSUE TITLE
Support ELSI

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/libmbd-feedstock#20]
ELSI is now available on conda-forge. Should we build libmbd with by default with support for ELSI when MPI is enabled?

**Comment by jhrmnn** [comment]
Sounds reasonable, I don't see why someone would want to use ScaLAPACK eigensolvers over ELPA.

**Comment by awvwgk** [comment]
There might be an issue with using ELSI's CMake config due to: https://gitlab.com/elsi_project/elsi_interface/-/issues/57

**Comment by jhrmnn** [comment]
I've linked Libmbd against ELSI via its CMake config multiple times without issues.

**Comment by awvwgk** [comment]
Unfortunately, the ELSI's CMake config is broken if you use any external dependency (ELPA, NTPoly, OMM), like I'm doing for the version on conda-forge.
