### ISSUE TITLE
MPI build broken: wrong version of ELPA linked

### ISSUE THREAD

**Issue by jhrmnn** [conda-forge/libmbd-feedstock#25]
```
$ otool -DL $CONDA_PREFIX/lib/libmbd.dylib | grep elpa
	@rpath/libelpa_openmp.15.dylib (compatibility version 17.0.0, current version 17.2.0)
$ exa -l $CONDA_PREFIX/lib/libelpa_openmp.*dylib
.rwxrwxr-x 1.5M jhermann 11 Jan 15:37 /Users/jhermann/Downloads/tmp/lib/libelpa_openmp.17.dylib
lrwxr-xr-x   23 jhermann 12 Jan 09:21 /Users/jhermann/Downloads/tmp/lib/libelpa_openmp.dylib -> libelpa_openmp.17.dylib
```
For now I can just rebuild Libmbd, but I'm not sure how to fix this properly so I don't have to rebuild every time a new ELPA version is released. Can we link Libmbd against `libelpa_openmp.dylib` without the version specifier? Or is pinning the ELPA version a way to go?

**Comment by awvwgk** [comment]
I pinned the ELPA version in ELSI now. I hope I set the pin tightly enough to avoid this link of linking issues.
